version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
      
    commands:
      - echo test
  build:
    commands:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - export PATH=$PWD/:$PATH
      - pip install kubernetes
      - aws --version
      - aws ec2 describe-regions
      - aws eks update-kubeconfig --region us-west-1 --name cluster1 --role-arn arn:aws:iam::123456789:role/EksCodeBuildkubectlRole55 #update this with your arn
      - ls -l
      - sleep 10
      - python build02/02_k8s_sec.py
      - kubectl apply -f build02/pod1.yaml
      - sleep 20
      - kubectl logs test-pod
      - sleep 10
      - kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -pyoperrosola -e "SELECT user FROM mysql.user;"